### PR TITLE
Update SqlDataProvider script to support minimum DNN requirements

### PR DESCRIPTION
**Pull request by david-poindexter**
In order to support the minimum SQL Server requirements for DNN, this script needed to be updated.  Also added support for `{databaseOwner}{objectQualifier}`.

### CODE REVIEW

**Review by valadas — CHANGES_REQUESTED** [review]
Looks like we have a bit too much in here :)

**Review by valadas — CHANGES_REQUESTED** [review]
And a little missing {databaseOwner}{objectQualifier} :)

**Review by valadas — APPROVED** [review]
Looks good to me. Thanks!

**Comment by WillStrohl** [comment]
I made some updates in #63 and #64

**Pull request merged**
