### PR TITLE
Removes syntax that's not Azure-compliant

### PR DESCRIPTION
**Pull request by WillStrohl**

### CODE REVIEW

**Review by david-poindexter — APPROVED** [review]
I don't have the ability to test this in Azure, but it does seem familiar that this would need to change in this manner.

**Comment by david-poindexter** [comment]
@valadas can you review and confirm?

**Review by mitchelsellers — APPROVED** [review]
This looks good to me, and tested against an Azure SQL Instance.  Thanks for the contribution @hismightiness

**Comment by david-poindexter** [comment]
> This looks good to me, and tested against an Azure SQL Instance. Thanks for the contribution @hismightiness

Perfect - thanks @mitchelsellers

**Comment by WillStrohl** [comment]
> I don't have the ability to test this in Azure, but it does seem familiar that this would need to change in this manner.

There are other minor Azure differences out there, but this is all that I noticed in this script.  Basically, these updates specifically are because SQL in Azure doesn't have a `primary` disk.  :)

**Pull request merged**
